name: C/C++ CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: [ubuntu-22.04]
    
    steps:
    - name: install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libboost-system-dev libboost-thread-dev libboost-log-dev googletest asciidoc source-highlight doxygen graphviz
    
    - name: checkout vsomeip
      uses: actions/checkout@master
      with:
        repository: COVESA/vsomeip
    
