name: C/C++ CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:18.04
      volumes:
        - .:/workspace
      options: >-
        --workdir=/workspace
      env:
        UID: 1000
        GID: 1000    
    steps:
      - name: Sanity check
        run: |
          uname -a
          cat /etc/os-release
          whoami
          echo "id -u: $(id -u)"
          echo "id -g: $(id -g)"
          pwd
          df -h
          mount
          echo "UID: $UID"
          echo "GID: $GID"
          echo "Current working directory: $(pwd)"
          ls -l /workspace
