name: C/C++ CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: [ubuntu-22.04]
    
     steps:
    - uses: actions/checkout@v2
    - name: install dependencies
    
    run: |
        sudo apt-get update -qq
        sudo apt-get install -y libboost-system-dev libboost-thread-dev libboost-log-dev googletest asciidoc source-highlight doxygen graphviz
