name: C/C++ CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: ubuntu:18.04
      volumes:
        - .:/workspace

    
    steps:
      - name: Sanity check
        run: |
          uname -a
          cat /etc/os-release
          whoami
          pwd
          df -h
          mount
